#! /bin/bash

sudo cp /pythonrepoinstall /usr/local/bin

sudo chown root: /usr/local/bin/pythonrepoinstall

sudo chmod 755 pythonrepoinstall



sudo cp /fileRead /usr/local/bin

sudo chown root: /usr/local/bin/fileRead

sudo chmod 755 fileRead